server:
  port: 8033

management:
  context-path: /monitor
  security:
    enabled: false

security:
    sessions: stateless
    filter-order: 15

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
  pattern:
    level: "%X{mdcData} %5p"

eureka:
  instance:
    preferIpAddress: true
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8022}/eureka/

token:
  accessTokenValiditySeconds: 7200
  refreshTokenValiditySeconds: 72000

# Data layer config.
spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://localhost/auth?verifyServerCertificate=false&useSSL=false
    username: dl_auth
    password: I9dj@
    driver-class-name: com.mysql.jdbc.Driver
