server:
  port: 8088

management:
  context-path: /monitor
  security:
    enabled: false

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    com.x.api: 'DEBUG'
  pattern:
    level: "%X{mdcData} %5p"
  path: logs
  file: ${logging.path}/${spring.application.name}

eureka:
  instance:
    preferIpAddress: true
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8022}/eureka/

# Zuul config.
endpoints.routes.enabled: false
endpoints.filters.enabled: false

zuul.routes:
  auth:
    path: /oauth/**
    stripPrefix: false
    sensitiveHeaders:
    serviceId: auth-server
