server:
  port: 8100

management:
  context-path: /monitor
  security:
    enabled: false

security:
    sessions: stateless
    filter-order: 5

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.mybatis: 'DEBUG'
    org.apache.ibatis: 'DEBUG'
    com.x.api.account: 'DEBUG'
  pattern:
    level: "%X{mdcData} %5p"

mybatis:
  config: classpath:mybatis-config.xml

eureka:
  instance:
    preferIpAddress: true
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8022}/eureka/

# Data layer config.
spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://localhost/auth?verifyServerCertificate=false&useSSL=false
    username: dl_auth
    password: I9dj@
    driver-class-name: com.mysql.jdbc.Driver
  cache:
    type: Redis
