server:
  port: 8022

management:
  context-path: /monitor
  security:
    enabled: false

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    appname: ${spring.application.name}
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10