server:
  port: 8011

management:
  context-path: /monitor
  security:
    enabled: false

security:
  user:
    name: application
    password: 6DuEkv1ohcIV

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

eureka:
  instance:
    preferIpAddress: true
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8022}/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pftx/config-repo.git
          basedir: target/config
